baseURL: "http://example.org/"
defaultContentLanguage: "en"

menu:
  main:
  - identifier: menu_home
    url: /
    weight: 1
  - identifier: menu_about
    url: /about/
    weight: 2
  - identifier: menu_contact
    url: /contact/
    weight: 3

languages:
  en:
    title: "Sofina Daria"
    contentDir: "content/en"
    languageName: "English"
    languageCode: "en-US"
  ru:
    title: "Софина Дарья"
    contentDir: "content/ru"
    languageName: "Русский"
    languageCode: "ru-RU"
